# Generated by Django 4.0.1 on 2022-03-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_profile_usertype'),
        ('AppDonation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='Accounts.district'),
            preserve_default=False,
        ),
    ]
