# Generated by Django 4.0.1 on 2022-03-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDonation', '0002_donations_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='supplied',
            field=models.BooleanField(default=False),
        ),
    ]
