# Generated by Django 4.0.1 on 2022-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDonation', '0004_alter_donations_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='supplied',
            new_name='distributed',
        ),
    ]
