# Generated by Django 4.0.1 on 2022-03-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDonation', '0006_donations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Distributed', 'Distributed')], max_length=15),
        ),
    ]
