# Generated by Django 4.0.1 on 2022-02-21 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=15)),
                ('nationalId', models.CharField(max_length=20)),
                ('emailAddress', models.EmailField(blank=True, max_length=100, null=True)),
                ('volunteerAddress', models.TextField(max_length=200)),
                ('isVolunteer', models.BooleanField(default=False)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
                ('volunteerDistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.district')),
                ('volunteerDivison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.division')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=15)),
                ('nationalId', models.CharField(max_length=20)),
                ('emailAddress', models.EmailField(blank=True, max_length=100, null=True)),
                ('donarAddress', models.TextField(max_length=200)),
                ('isDonor', models.BooleanField(default=False)),
                ('donarDistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.district')),
                ('donarDivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.division')),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
