# Generated by Django 4.0.1 on 2022-02-21 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_donor_emailaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='lastName',
        ),
        migrations.AddField(
            model_name='donor',
            name='Name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
