# Generated by Django 4.0.1 on 2022-02-21 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_donaraddress_donor_donoraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='donor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='signupTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='volunteer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='signupTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
