# Generated by Django 4.0.1 on 2022-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_donor_profile_pic_donor_signuptime_donor_updatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='donor'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='volunteer'),
        ),
    ]
