# Generated by Django 4.0.1 on 2022-03-14 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0007_remove_donor_name_remove_volunteer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=15)),
                ('nationalId', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile')),
                ('userType', models.IntegerField(choices=[(1, 'Donor'), (2, 'Volunteer')])),
                ('verified', models.BooleanField(default=False)),
                ('signupTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.district')),
                ('divison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.division')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
