# Generated by Django 4.0.1 on 2022-03-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.CharField(choices=[(1, 'Donor'), (2, 'Volunteer')], max_length=20),
        ),
    ]
