# Generated by Django 4.0.1 on 2022-03-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_profile_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteerDistrict',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteerDivison',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
