# Generated by Django 4.0.1 on 2022-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_volunteer_volunteer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Donor'), (2, 'Volunteer')]),
        ),
    ]
