# Generated by Django 4.0.1 on 2022-04-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.IntegerField(choices=[(1, 'Donor'), (2, 'Volunteer'), (3, 'Staff')]),
        ),
    ]
