# Generated by Django 4.0.1 on 2022-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedbackTopic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
